### PR TITLE
add basic projects and configurations

### LINKED ISSUE #3: Add Data Crawler and Archive Manager empty python projects

### PR DESCRIPTION
**Pull request by ZPoreba**

### CODE REVIEW

**Comment by SzymonSmykala** [comment]
do we need django? We won't expose any endpoint here. We will download data from TTSS and save it into db

**Review by SzymonSmykala — CHANGES_REQUESTED** [review]
do we need django? We won't expose any endpoint here. We will download data from TTSS and save it into db.
Basically it will be azure function (you don't need to setup here) 
reference:
https://azure.microsoft.com/pl-pl/blog/taking-a-closer-look-at-python-support-for-azure-functions/

**Comment by ZPoreba** [comment]
> do we need django? We won't expose any endpoint here. We will download data from TTSS and save it into db.
> Basically it will be azure function (you don't need to setup here)
> reference:
> https://azure.microsoft.com/pl-pl/blog/taking-a-closer-look-at-python-support-for-azure-functions/

Django is not only for communication with client. It provides many mechanisms that make access to database easier. Eg. models and serializers. I would say that it rather has bigger impact on database communication and make it way easier

**Comment by SzymonSmykala** [comment]
> > do we need django? We won't expose any endpoint here. We will download data from TTSS and save it into db.
> > Basically it will be azure function (you don't need to setup here)
> > reference:
> > https://azure.microsoft.com/pl-pl/blog/taking-a-closer-look-at-python-support-for-azure-functions/
> 
> Django is not only for communication with client. It provides many mechanisms that make access to database easier. Eg. models and serializers. I would say that it rather has bigger impact on database communication and make it way easier

awesome!

**Review by SzymonSmykala — APPROVED** [review]

**Review by Nika96 — APPROVED** [review]

**Pull request merged**
